name: ci-deploy-dbt-project
on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt + Snowflake CLI
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-snowflake==1.9.*"
          # Snowflake CLI 3.9.0+ required for `snow dbt` commands
          pip install "snowflake-cli-labs>=3.9.0"

      # -------- DBT (local) ----------
      # Make sure profiles.yml exists at repo root; no creds needed for deps/compile.
      - name: dbt deps
        run: dbt deps

      # - name: dbt compile (sanity)
      #   run: dbt compile

      # -------- DEPLOY ---------------
      # Deploys a DBT PROJECT object at dbt_projects.dev.jaffle_shop,
      # uploading files from the repo (incl. dbt_packages from the deps step).
      - name: Deploy DBT PROJECT (DEV)
        env:
          SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:      ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD:  ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE:      SYSADMIN     # e.g., SYSADMIN or a runner role
          SNOWFLAKE_WAREHOUSE: ANALYST_WH_DEV # e.g., WH_DEV
        run: |
          snow dbt deploy dbt_projects.dev.jaffle_shop_test \
            --source . \
            --profiles-dir . \
            --database dbt_projects \
            --schema dev \
            --role "$SNOWFLAKE_ROLE" \
            --warehouse "$SNOWFLAKE_WAREHOUSE" \
            --account "$SNOWFLAKE_ACCOUNT" \
            --user "$SNOWFLAKE_USER" \
            -x
