-- dbt_deploy/semantic_view_jaffle.sql

USE WAREHOUSE {{ wh }};
USE DATABASE ANALYTICS_{{ env }};
USE SCHEMA JAFFLE_SHOP_{{ env }};

CREATE OR REPLACE SEMANTIC VIEW JAFFLE_SHOP_DBT_SEMANTIC_VIEW
  TABLES (
    CUSTOMERS    AS CUSTOMERS      PRIMARY KEY (CUSTOMER_ID)   COMMENT = 'Customers dimension from dbt marts',
    LOCATIONS    AS LOCATIONS      PRIMARY KEY (LOCATION_ID)   COMMENT = 'Business locations and tax rates',
    ORDERS       AS ORDERS         PRIMARY KEY (ORDER_ID)      COMMENT = 'Orders fact from dbt marts',
    ORDER_ITEMS  AS ORDER_ITEMS    PRIMARY KEY (ORDER_ITEM_ID) COMMENT = 'Items within orders',
    PRODUCTS     AS PRODUCTS       PRIMARY KEY (PRODUCT_ID)    COMMENT = 'Product catalog',
    SUPPLIES     AS SUPPLIES       PRIMARY KEY (SUPPLY_ID)     COMMENT = 'Supply items and costs'
  )
  RELATIONSHIPS (
    ORDERS (CUSTOMER_ID)           REFERENCES CUSTOMERS (CUSTOMER_ID),
    ORDERS (LOCATION_ID)           REFERENCES LOCATIONS (LOCATION_ID),
    ORDER_ITEMS (ORDER_ID)         REFERENCES ORDERS (ORDER_ID),
    ORDER_ITEMS (PRODUCT_ID)       REFERENCES PRODUCTS (PRODUCT_ID),
    SUPPLIES (PRODUCT_ID)          REFERENCES PRODUCTS (PRODUCT_ID)
  )
  FACTS (
    -- CUSTOMERS
    CUSTOMERS.COUNT_LIFETIME_ORDERS AS COUNT_LIFETIME_ORDERS,
    CUSTOMERS.LIFETIME_SPEND        AS LIFETIME_SPEND,
    CUSTOMERS.LIFETIME_SPEND_PRETAX AS LIFETIME_SPEND_PRETAX,
    CUSTOMERS.LIFETIME_TAX_PAID     AS LIFETIME_TAX_PAID,

    -- LOCATIONS
    LOCATIONS.TAX_RATE              AS TAX_RATE,

    -- ORDERS
    ORDERS.COUNT_DRINK_ITEMS        AS COUNT_DRINK_ITEMS,
    ORDERS.COUNT_FOOD_ITEMS         AS COUNT_FOOD_ITEMS,
    ORDERS.COUNT_ORDER_ITEMS        AS COUNT_ORDER_ITEMS,
    ORDERS.CUSTOMER_ORDER_NUMBER    AS CUSTOMER_ORDER_NUMBER,
    ORDERS.ORDER_COST               AS ORDER_COST,
    ORDERS.ORDER_ITEMS_SUBTOTAL     AS ORDER_ITEMS_SUBTOTAL,
    ORDERS.ORDER_TOTAL              AS ORDER_TOTAL,
    ORDERS.ORDER_TOTAL_CENTS        AS ORDER_TOTAL_CENTS,
    ORDERS.SUBTOTAL                 AS SUBTOTAL,
    ORDERS.SUBTOTAL_CENTS           AS SUBTOTAL_CENTS,
    ORDERS.TAX_PAID                 AS TAX_PAID,
    ORDERS.TAX_PAID_CENTS           AS TAX_PAID_CENTS,

    -- ORDER_ITEMS
    ORDER_ITEMS.PRODUCT_PRICE       AS PRODUCT_PRICE,
    ORDER_ITEMS.SUPPLY_COST         AS SUPPLY_COST,

    -- PRODUCTS
    PRODUCTS.PRODUCT_PRICE          AS PRODUCT_PRICE,

    -- SUPPLIES
    SUPPLIES.SUPPLY_COST            AS SUPPLY_COST
  )
  DIMENSIONS (
    -- CUSTOMERS (include time dims as regular dimensions)
    CUSTOMERS.CUSTOMER_ID        AS CUSTOMER_ID,
    CUSTOMERS.CUSTOMER_NAME      AS CUSTOMER_NAME,
    CUSTOMERS.CUSTOMER_TYPE      AS CUSTOMER_TYPE,
    CUSTOMERS.FIRST_ORDERED_AT   AS FIRST_ORDERED_AT,
    CUSTOMERS.LAST_ORDERED_AT    AS LAST_ORDERED_AT,

    -- LOCATIONS
    LOCATIONS.LOCATION_ID        AS LOCATION_ID,
    LOCATIONS.LOCATION_NAME      AS LOCATION_NAME,
    LOCATIONS.OPENED_DATE        AS OPENED_DATE,

    -- ORDERS
    ORDERS.CUSTOMER_ID           AS CUSTOMER_ID,
    ORDERS.IS_DRINK_ORDER        AS IS_DRINK_ORDER,
    ORDERS.IS_FOOD_ORDER         AS IS_FOOD_ORDER,
    ORDERS.LOCATION_ID           AS LOCATION_ID,
    ORDERS.ORDER_ID              AS ORDER_ID,
    ORDERS.ORDERED_AT            AS ORDERED_AT,

    -- ORDER_ITEMS
    ORDER_ITEMS.IS_DRINK_ITEM    AS IS_DRINK_ITEM,
    ORDER_ITEMS.IS_FOOD_ITEM     AS IS_FOOD_ITEM,
    ORDER_ITEMS.ORDER_ID         AS ORDER_ID,
    ORDER_ITEMS.ORDER_ITEM_ID    AS ORDER_ITEM_ID,
    ORDER_ITEMS.PRODUCT_ID       AS PRODUCT_ID,
    ORDER_ITEMS.PRODUCT_NAME     AS PRODUCT_NAME,
    ORDER_ITEMS.ORDERED_AT       AS ORDERED_AT,

    -- PRODUCTS
    PRODUCTS.IS_DRINK_ITEM       AS IS_DRINK_ITEM,
    PRODUCTS.IS_FOOD_ITEM        AS IS_FOOD_ITEM,
    PRODUCTS.PRODUCT_DESCRIPTION AS PRODUCT_DESCRIPTION,
    PRODUCTS.PRODUCT_ID          AS PRODUCT_ID,
    PRODUCTS.PRODUCT_NAME        AS PRODUCT_NAME,
    PRODUCTS.PRODUCT_TYPE        AS PRODUCT_TYPE,

    -- SUPPLIES
    SUPPLIES.IS_PERISHABLE_SUPPLY AS IS_PERISHABLE_SUPPLY,
    SUPPLIES.PRODUCT_ID           AS PRODUCT_ID,
    SUPPLIES.SUPPLY_ID            AS SUPPLY_ID,
    SUPPLIES.SUPPLY_NAME          AS SUPPLY_NAME,
    SUPPLIES.SUPPLY_UUID          AS SUPPLY_UUID
  )
  COMMENT = 'Semantic view for Jaffle Shop analytics (DBT marts)'
  COPY GRANTS
;

GRANT SELECT, REFERENCES
  ON SEMANTIC VIEW JAFFLE_SHOP_DBT_SEMANTIC_VIEW
  TO ROLE PUBLIC;
