-- dbt_deploy/semantic_view_jaffle.sql
-- Params expected via EXECUTE IMMEDIATE FROM ... USING (…):
--   db_name, env, wh, semantic_view_name
-- Example values are passed from deploy_parametrized.sql

USE WAREHOUSE {{ wh }};

USE DATABASE ANALYTICS_{{ env }};

USE SCHEMA JAFFLE_SHOP_{{ env }};

CREATE OR REPLACE SEMANTIC VIEW JAFFLE_SHOP_DBT_SEMANTIC_VIEW
  TABLES (
    CUSTOMERS  AS CUSTOMERS
      PRIMARY KEY (CUSTOMER_ID)
      COMMENT = 'Customers dimension from dbt marts',
    LOCATIONS  AS LOCATIONS
      PRIMARY KEY (LOCATION_ID)
      COMMENT = 'Business locations and tax rates',
    ORDERS     AS ORDERS
      PRIMARY KEY (ORDER_ID)
      COMMENT = 'Orders fact from dbt marts',
    ORDER_ITEMS AS ORDER_ITEMS
      PRIMARY KEY (ORDER_ITEM_ID)
      COMMENT = 'Items within orders',
    PRODUCTS   AS PRODUCTS
      PRIMARY KEY (PRODUCT_ID)
      COMMENT = 'Product catalog',
    SUPPLIES   AS SUPPLIES
      PRIMARY KEY (SUPPLY_ID)
      COMMENT = 'Supply items and costs'
  )
  RELATIONSHIPS (
    ORDERS (CUSTOMER_ID)           REFERENCES CUSTOMERS,
    ORDERS (LOCATION_ID)           REFERENCES LOCATIONS,
    ORDER_ITEMS (ORDER_ID)         REFERENCES ORDERS,
    ORDER_ITEMS (PRODUCT_ID)       REFERENCES PRODUCTS,
    SUPPLIES (PRODUCT_ID)          REFERENCES PRODUCTS
  )
  /* Order of clauses matters: FACTS before DIMENSIONS. */
  FACTS (
    /* CUSTOMERS facts */
    PUBLIC CUSTOMERS.COUNT_LIFETIME_ORDERS   AS COUNT_LIFETIME_ORDERS,
    PUBLIC CUSTOMERS.LIFETIME_SPEND          AS LIFETIME_SPEND,
    PUBLIC CUSTOMERS.LIFETIME_SPEND_PRETAX   AS LIFETIME_SPEND_PRETAX,
    PUBLIC CUSTOMERS.LIFETIME_TAX_PAID       AS LIFETIME_TAX_PAID,

    /* LOCATIONS facts */
    PUBLIC LOCATIONS.TAX_RATE                AS TAX_RATE,

    /* ORDERS facts */
    PUBLIC ORDERS.COUNT_DRINK_ITEMS          AS COUNT_DRINK_ITEMS,
    PUBLIC ORDERS.COUNT_FOOD_ITEMS           AS COUNT_FOOD_ITEMS,
    PUBLIC ORDERS.COUNT_ORDER_ITEMS          AS COUNT_ORDER_ITEMS,
    PUBLIC ORDERS.CUSTOMER_ORDER_NUMBER      AS CUSTOMER_ORDER_NUMBER,
    PUBLIC ORDERS.ORDER_COST                 AS ORDER_COST,
    PUBLIC ORDERS.ORDER_ITEMS_SUBTOTAL       AS ORDER_ITEMS_SUBTOTAL,
    PUBLIC ORDERS.ORDER_TOTAL                AS ORDER_TOTAL,
    PUBLIC ORDERS.ORDER_TOTAL_CENTS          AS ORDER_TOTAL_CENTS,
    PUBLIC ORDERS.SUBTOTAL                   AS SUBTOTAL,
    PUBLIC ORDERS.SUBTOTAL_CENTS             AS SUBTOTAL_CENTS,
    PUBLIC ORDERS.TAX_PAID                   AS TAX_PAID,
    PUBLIC ORDERS.TAX_PAID_CENTS             AS TAX_PAID_CENTS,

    /* ORDER_ITEMS facts */
    PUBLIC ORDER_ITEMS.PRODUCT_PRICE         AS ORDER_ITEM_PRODUCT_PRICE,
    PUBLIC ORDER_ITEMS.SUPPLY_COST           AS ORDER_ITEM_SUPPLY_COST,

    /* PRODUCTS facts */
    PUBLIC PRODUCTS.PRODUCT_PRICE            AS PRODUCT_PRICE,

    /* SUPPLIES facts */
    PUBLIC SUPPLIES.SUPPLY_COST              AS SUPPLY_COST
  )
  DIMENSIONS (
    /* CUSTOMERS dims + time dims */
    CUSTOMERS.CUSTOMER_ID,
    CUSTOMERS.CUSTOMER_NAME,
    CUSTOMERS.CUSTOMER_TYPE,
    CUSTOMERS.FIRST_ORDERED_AT,
    CUSTOMERS.LAST_ORDERED_AT,

    /* LOCATIONS dims + time dims */
    LOCATIONS.LOCATION_ID,
    LOCATIONS.LOCATION_NAME,
    LOCATIONS.OPENED_DATE,

    /* ORDERS dims + time dims */
    ORDERS.CUSTOMER_ID,
    ORDERS.IS_DRINK_ORDER,
    ORDERS.IS_FOOD_ORDER,
    ORDERS.LOCATION_ID,
    ORDERS.ORDER_ID,
    ORDERS.ORDERED_AT,

    /* ORDER_ITEMS dims + time dims */
    ORDER_ITEMS.IS_DRINK_ITEM,
    ORDER_ITEMS.IS_FOOD_ITEM,
    ORDER_ITEMS.ORDER_ID,
    ORDER_ITEMS.ORDER_ITEM_ID,
    ORDER_ITEMS.PRODUCT_ID,
    ORDER_ITEMS.PRODUCT_NAME,
    ORDER_ITEMS.ORDERED_AT,

    /* PRODUCTS dims */
    PRODUCTS.IS_DRINK_ITEM,
    PRODUCTS.IS_FOOD_ITEM,
    PRODUCTS.PRODUCT_DESCRIPTION,
    PRODUCTS.PRODUCT_ID,
    PRODUCTS.PRODUCT_NAME,
    PRODUCTS.PRODUCT_TYPE,

    /* SUPPLIES dims */
    SUPPLIES.IS_PERISHABLE_SUPPLY,
    SUPPLIES.PRODUCT_ID,
    SUPPLIES.SUPPLY_ID,
    SUPPLIES.SUPPLY_NAME,
    SUPPLIES.SUPPLY_UUID
  )
  COMMENT = 'Semantic view for Jaffle Shop analytics (DBT marts)'
  COPY GRANTS;


GRANT SELECT, REFERENCES
  ON SEMANTIC VIEW JAFFLE_SHOP_DBT_SEMANTIC_VIEW
  TO ROLE PUBLIC;
