name: ci-deploy-dbt-project
on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python + dbt + Snowflake CLI
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-snowflake==1.9.*"
          pip install "snowflake-cli-labs==3.9.*"

      # (Optional) set SNOWFLAKE_ envs for profiles.yml templating
      - name: dbt deps (Hub/local only)
        run: dbt deps

      - name: dbt build smoke
        run: dbt build --select state:modified+ --defer --state target

      - name: Deploy to Snowflake dbt project object
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:    ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE:    SYSADMIN
          SNOWFLAKE_WAREHOUSE: ANALYST_WH_DEV
        run: |
          # Creates/updates the dbt project object by uploading local files
          snow dbt deploy dbt_projects.dev.jaffle_shop_test --project-dir . --profiles-dir .
