name: ci-deploy-dbt-project

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # Point dbt to the CI-only profiles.yml
      DBT_PROFILES_DIR: ${{ github.workspace }}/.github/utils

      # Secrets used by the CI profile + CLI flags
      SNOWFLAKE_ACCOUNT:       ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER:          ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD:      ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE:          SYSADMIN     # e.g., SYSADMIN or a runner role
      # SNOWFLAKE_ROLE_DEV:      ${{ secrets.SNOWFLAKE_ROLE_DEV }}
      # SNOWFLAKE_ROLE_PROD:     ${{ secrets.SNOWFLAKE_ROLE_PROD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt + Snowflake CLI (compatible)
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-snowflake==1.10.*"
          pip install "snowflake-cli-labs>=3.11.0"
          dbt --version
          snow --version

      # Make dbt see cicd_profiles.yml as profiles.yml
      - name: Prepare CI profile
        run: |
          cp .github/utils/cicd_profiles.yml .github/utils/profiles.yml

      - name: dbt deps
        run: dbt deps

      # ---------- PR: compile + DEV deploy ----------
      - name: dbt compile (PR -> DEV)
        if: github.event_name == 'pull_request'
        run: dbt compile --target dev

      - name: Deploy DBT PROJECT (DEV)
        if: github.event_name == 'pull_request'
        run: |
          snow dbt deploy dbt_projects.dev.jaffle_shop_test \
            --source . \
            --profiles-dir . \
            --database dbt_projects \
            --schema dev \
            --role "$SNOWFLAKE_ROLE" \
            --warehouse ANALYST_WH_DEV \
            --account "$SNOWFLAKE_ACCOUNT" \
            --user "$SNOWFLAKE_USER" \
            -x

      # ---------- MAIN: PROD deploy on merge ----------
      - name: Deploy DBT PROJECT (PROD)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          snow dbt deploy dbt_projects.dev.jaffle_shop_test \
            --source . \
            --profiles-dir . \
            --database dbt_projects \
            --schema dev \
            --role "$SNOWFLAKE_ROLE" \
            --warehouse ANALYST_WH_PROD \
            --account "$SNOWFLAKE_ACCOUNT" \
            --user "$SNOWFLAKE_USER" \
            -x
